version: '3.9'

services:
  app:
    build: .
    container_name: blossomer-gtm-app
    command: gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 app.api.main:app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    restart: on-failure
    # Uncomment and configure the following if you add a database service
    # depends_on:
    #   - db

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: youruser
  #     POSTGRES_PASSWORD: yourpassword
  #     POSTGRES_DB: blossomer
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: 